import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ExternalLink, Heart, Users, Target } from "lucide-react";

const About = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-secondary/20 py-8">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold mb-2">ℹ️ About NutriScan</h1>
          <p className="text-muted-foreground text-lg">
            Our mission, technology, and team
          </p>
        </div>

        <Card className="mb-6 shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-2xl">
              <Target className="h-6 w-6 text-primary" />
              Our Mission
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-muted-foreground">
            <p className="text-lg leading-relaxed">
              NutriScan was created as a comprehensive nutrition analysis platform to help people make 
              informed decisions about their diet and health. Our goal is to combine real-time nutrition 
              data with AI-powered recommendations to make healthy eating accessible and personalized for everyone.
            </p>
            <p className="leading-relaxed">
              This project demonstrates how modern web technologies and AI can be leveraged to solve 
              real-world health challenges. By integrating the Nutritionix API for accurate nutrition data 
              and Gemini AI for intelligent meal planning, we provide users with a complete nutrition companion.
            </p>
          </CardContent>
        </Card>

        <Card className="mb-6 shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-2xl">
              <Heart className="h-6 w-6 text-primary" />
              Key Features
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="p-4 bg-primary/5 rounded-lg">
                <div className="font-semibold mb-2 text-lg">🔍 Food Analyzer</div>
                <p className="text-sm text-muted-foreground">
                  Real-time nutrition data from Nutritionix API with AI-suggested healthier alternatives
                </p>
              </div>
              <div className="p-4 bg-primary/5 rounded-lg">
                <div className="font-semibold mb-2 text-lg">🤖 AI Diet Planner</div>
                <p className="text-sm text-muted-foreground">
                  Personalized meal plans generated by Gemini AI based on your goals and preferences
                </p>
              </div>
              <div className="p-4 bg-primary/5 rounded-lg">
                <div className="font-semibold mb-2 text-lg">📝 Diet Tracker</div>
                <p className="text-sm text-muted-foreground">
                  Log daily meals and monitor your calorie and macro intake in real-time
                </p>
              </div>
              <div className="p-4 bg-primary/5 rounded-lg">
                <div className="font-semibold mb-2 text-lg">📊 Insights</div>
                <p className="text-sm text-muted-foreground">
                  Visualize nutrition trends with interactive charts and analytics
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="mb-6 shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-2xl">
              <Users className="h-6 w-6 text-primary" />
              Technology Stack
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-primary"></div>
                <span><strong>Frontend:</strong> React, TypeScript, Tailwind CSS, shadcn/ui</span>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-primary"></div>
                <span><strong>Backend:</strong> Lovable Cloud (Supabase Edge Functions)</span>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-primary"></div>
                <span><strong>APIs:</strong> Nutritionix (nutrition data), Gemini AI (meal planning)</span>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-primary"></div>
                <span><strong>Charts:</strong> Recharts for data visualization</span>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-lg bg-gradient-to-br from-primary/10 to-accent/10 border-primary/20">
          <CardHeader>
            <CardTitle className="text-2xl">📝 Share Your Feedback</CardTitle>
            <CardDescription className="text-base">
              Help us improve NutriScan by sharing your thoughts and suggestions
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button asChild size="lg" className="w-full">
              <a 
                href="https://forms.google.com/your-form-link" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center justify-center gap-2"
              >
                <ExternalLink className="h-5 w-5" />
                Fill Feedback Form
              </a>
            </Button>
            <p className="text-sm text-muted-foreground mt-4 text-center">
              Your feedback helps us create better nutrition tools for everyone
            </p>
          </CardContent>
        </Card>

        <div className="mt-8 p-6 bg-muted/50 rounded-lg text-center">
          <p className="text-sm text-muted-foreground">
            <strong>Academic Project:</strong> NutriScan was developed as a college CEP project 
            to demonstrate the integration of modern web technologies, real-time APIs, and AI for health applications.
          </p>
        </div>
      </div>
    </div>
  );
};

export default About;
